# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-DKIM
version:      0.23
version_from: lib/Mail/DKIM.pm
installdirs:  site
requires:
    Crypt::OpenSSL::RSA:           0
    Digest::SHA:                   0
    Digest::SHA1:                  0
    Error:                         0
    Mail::Address:                 0
    MIME::Base64:                  0
    Net::DNS:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
